version: '3.8'

services:
  postgres:
    container_name: socialmediadb
    image: postgres:13
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./dockerConfig/postgres-dev-init.sql:/docker-entrypoint-initdb.d/init.sql # will setup dev database adonis_app for us

    environment:
      POSTGRES_USER: adonis
      POSTGRES_PASSWORD: adonis
    ports:
      - 5432:5432

  redis:
    container_name: redisdb
    image: redis:6-alpine
    volumes:
      - redis_volume:/data
    ports:
      - 6379:6379

volumes:
  postgres_volume:
  redis_volume:
